CREATE TABLE [dbo].[fin_Customers] (
    [customerId]                    INT           NOT NULL,
    [customerCode]                  VARCHAR (5)   NULL,
    [customerURL]                   VARCHAR (300) NULL,
    [customerTitle]                 VARCHAR (50)  NOT NULL,
    [customerDescription]           VARCHAR (500) NULL,
    [customerProductType]           INT           NULL,
    [customerAddressLine1]          VARCHAR (500) NULL,
    [customerAddressLine2]          VARCHAR (500) NULL,
    [customerCity]                  VARCHAR (100) NULL,
    [customerZip]                   VARCHAR (10)  NULL,
    [customerState]                 VARCHAR (50)  NULL,
    [customerStateShortcode]        VARCHAR (5)   NULL,
    [customerCountry]               VARCHAR (50)  NULL,
    [customerCountryShortcode]      VARCHAR (5)   NULL,
    [customerIsActive]              BIT           NULL,
    [customerEmail]                 VARCHAR (100) NULL,
    [customerEmailAlt]              VARCHAR (100) NULL,
    [customerPhone]                 VARCHAR (15)  NULL,
    [customerPhoneAlt]              VARCHAR (15)  NULL,
    [customerMinQty]                INT           NULL,
    [customerMaxQty]                INT           NULL,
    [customerOrderIntimationEmal]   VARCHAR (100) NULL,
    [customerSampleIntimationEmail] VARCHAR (100) NULL,
    [customerFTP]                   VARCHAR (100) NULL,
    [customerFtpUsername]           VARCHAR (100) NULL,
    [customerFtpPassword]           VARCHAR (100) NULL,
    [customerSendOnFtp]             BIT           NULL,
    [customerFirstName]             NVARCHAR (50) NULL,
    [customerLastName]              NVARCHAR (50) NULL,
    [customerAccountId]             INT           NULL,
    [customerCreatedOn]             DATETIME      NULL,
    [customerCreatedBy]             INT           NULL,
    [customerCreatedIP]             VARCHAR (50)  NULL,
    CONSTRAINT [PK_Product_customers] PRIMARY KEY CLUSTERED ([customerId] ASC)
);

