CREATE TABLE [dbo].[fin_Vendors] (
    [vendorId]                    INT           NOT NULL,
    [vendorCode]                  VARCHAR (5)   NULL,
    [vendorURL]                   VARCHAR (300) NULL,
    [vendorTitle]                 VARCHAR (50)  NOT NULL,
    [vendorDescription]           VARCHAR (500) NULL,
    [vendorProductType]           INT           NULL,
    [vendorAddressLine1]          VARCHAR (500) NULL,
    [vendorAddressLine2]          VARCHAR (500) NULL,
    [vendorCity]                  VARCHAR (100) NULL,
    [vendorZip]                   VARCHAR (10)  NULL,
    [vendorState]                 VARCHAR (50)  NULL,
    [vendorStateShortcode]        VARCHAR (5)   NULL,
    [vendorCountry]               VARCHAR (50)  NULL,
    [vendorCountryShortcode]      VARCHAR (5)   NULL,
    [vendorIsActive]              BIT           NULL,
    [vendorEmail]                 VARCHAR (100) NULL,
    [vendorEmailAlt]              VARCHAR (100) NULL,
    [vendorPhone]                 VARCHAR (15)  NULL,
    [vendorPhoneAlt]              VARCHAR (15)  NULL,
    [vendorMinQty]                INT           NULL,
    [vendorMaxQty]                INT           NULL,
    [vendorOrderIntimationEmal]   VARCHAR (100) NULL,
    [vendorSampleIntimationEmail] VARCHAR (100) NULL,
    [vendorFTP]                   VARCHAR (100) NULL,
    [vendorFtpUsername]           VARCHAR (100) NULL,
    [vendorFtpPassword]           VARCHAR (100) NULL,
    [vendorSendOnFtp]             BIT           NULL,
    [vendorFirstName]             NVARCHAR (50) NULL,
    [vendorLastName]              NVARCHAR (50) NULL,
    [vendorAccountId]             INT           NULL,
    [vendorCreatedOn]             DATETIME      NULL,
    [vendorCreatedBy]             INT           NULL,
    [vendorCreatedIP]             VARCHAR (50)  NULL,
    CONSTRAINT [PK_Product_Vendors] PRIMARY KEY CLUSTERED ([vendorId] ASC)
);

