//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinPro.FinProSyncService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="objAccount", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class objAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int accountIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string accountPrefixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string accountNoField;
        
        private System.Nullable<int> accountLevelField;
        
        private System.Nullable<int> accountParentField;
        
        private System.Nullable<int> accountTypeField;
        
        private System.Nullable<int> associateIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string accountTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string accountDescriptionField;
        
        private System.DateTime accountCreatedOnField;
        
        private System.Nullable<int> accountCreatedByField;
        
        private System.Nullable<System.DateTime> accountLastUpdatedField;
        
        private System.Nullable<int> accountLastUpdatedByField;
        
        private decimal accountLedgerField;
        
        private decimal accountActualField;
        
        private System.Nullable<int> accountDefaultVersaAccountField;
        
        private bool accountIsBudgetDependentField;
        
        private bool accountIsActiveField;
        
        private bool accountIsVisibleField;
        
        private int accountIsTransactableField;
        
        private int accountSystemIndexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int accountID {
            get {
                return this.accountIDField;
            }
            set {
                if ((this.accountIDField.Equals(value) != true)) {
                    this.accountIDField = value;
                    this.RaisePropertyChanged("accountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string accountPrefix {
            get {
                return this.accountPrefixField;
            }
            set {
                if ((object.ReferenceEquals(this.accountPrefixField, value) != true)) {
                    this.accountPrefixField = value;
                    this.RaisePropertyChanged("accountPrefix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string accountNo {
            get {
                return this.accountNoField;
            }
            set {
                if ((object.ReferenceEquals(this.accountNoField, value) != true)) {
                    this.accountNoField = value;
                    this.RaisePropertyChanged("accountNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> accountLevel {
            get {
                return this.accountLevelField;
            }
            set {
                if ((this.accountLevelField.Equals(value) != true)) {
                    this.accountLevelField = value;
                    this.RaisePropertyChanged("accountLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> accountParent {
            get {
                return this.accountParentField;
            }
            set {
                if ((this.accountParentField.Equals(value) != true)) {
                    this.accountParentField = value;
                    this.RaisePropertyChanged("accountParent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> accountType {
            get {
                return this.accountTypeField;
            }
            set {
                if ((this.accountTypeField.Equals(value) != true)) {
                    this.accountTypeField = value;
                    this.RaisePropertyChanged("accountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> associateID {
            get {
                return this.associateIDField;
            }
            set {
                if ((this.associateIDField.Equals(value) != true)) {
                    this.associateIDField = value;
                    this.RaisePropertyChanged("associateID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string accountTitle {
            get {
                return this.accountTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.accountTitleField, value) != true)) {
                    this.accountTitleField = value;
                    this.RaisePropertyChanged("accountTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string accountDescription {
            get {
                return this.accountDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.accountDescriptionField, value) != true)) {
                    this.accountDescriptionField = value;
                    this.RaisePropertyChanged("accountDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime accountCreatedOn {
            get {
                return this.accountCreatedOnField;
            }
            set {
                if ((this.accountCreatedOnField.Equals(value) != true)) {
                    this.accountCreatedOnField = value;
                    this.RaisePropertyChanged("accountCreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<int> accountCreatedBy {
            get {
                return this.accountCreatedByField;
            }
            set {
                if ((this.accountCreatedByField.Equals(value) != true)) {
                    this.accountCreatedByField = value;
                    this.RaisePropertyChanged("accountCreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.Nullable<System.DateTime> accountLastUpdated {
            get {
                return this.accountLastUpdatedField;
            }
            set {
                if ((this.accountLastUpdatedField.Equals(value) != true)) {
                    this.accountLastUpdatedField = value;
                    this.RaisePropertyChanged("accountLastUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.Nullable<int> accountLastUpdatedBy {
            get {
                return this.accountLastUpdatedByField;
            }
            set {
                if ((this.accountLastUpdatedByField.Equals(value) != true)) {
                    this.accountLastUpdatedByField = value;
                    this.RaisePropertyChanged("accountLastUpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public decimal accountLedger {
            get {
                return this.accountLedgerField;
            }
            set {
                if ((this.accountLedgerField.Equals(value) != true)) {
                    this.accountLedgerField = value;
                    this.RaisePropertyChanged("accountLedger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public decimal accountActual {
            get {
                return this.accountActualField;
            }
            set {
                if ((this.accountActualField.Equals(value) != true)) {
                    this.accountActualField = value;
                    this.RaisePropertyChanged("accountActual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public System.Nullable<int> accountDefaultVersaAccount {
            get {
                return this.accountDefaultVersaAccountField;
            }
            set {
                if ((this.accountDefaultVersaAccountField.Equals(value) != true)) {
                    this.accountDefaultVersaAccountField = value;
                    this.RaisePropertyChanged("accountDefaultVersaAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public bool accountIsBudgetDependent {
            get {
                return this.accountIsBudgetDependentField;
            }
            set {
                if ((this.accountIsBudgetDependentField.Equals(value) != true)) {
                    this.accountIsBudgetDependentField = value;
                    this.RaisePropertyChanged("accountIsBudgetDependent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public bool accountIsActive {
            get {
                return this.accountIsActiveField;
            }
            set {
                if ((this.accountIsActiveField.Equals(value) != true)) {
                    this.accountIsActiveField = value;
                    this.RaisePropertyChanged("accountIsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public bool accountIsVisible {
            get {
                return this.accountIsVisibleField;
            }
            set {
                if ((this.accountIsVisibleField.Equals(value) != true)) {
                    this.accountIsVisibleField = value;
                    this.RaisePropertyChanged("accountIsVisible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public int accountIsTransactable {
            get {
                return this.accountIsTransactableField;
            }
            set {
                if ((this.accountIsTransactableField.Equals(value) != true)) {
                    this.accountIsTransactableField = value;
                    this.RaisePropertyChanged("accountIsTransactable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public int accountSystemIndex {
            get {
                return this.accountSystemIndexField;
            }
            set {
                if ((this.accountSystemIndexField.Equals(value) != true)) {
                    this.accountSystemIndexField = value;
                    this.RaisePropertyChanged("accountSystemIndex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="objTransaction", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class objTransaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int transIDField;
        
        private System.Nullable<int> transSystemIndexField;
        
        private System.Nullable<int> transParticipantIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transRefIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transAttachedFilesField;
        
        private System.Nullable<int> transInvoiceIDField;
        
        private System.Nullable<int> transDrAccountField;
        
        private System.Nullable<int> transCrAccountField;
        
        private System.Nullable<int> deptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transNarrationField;
        
        private decimal transAmountField;
        
        private System.DateTime transCreatedOnField;
        
        private int transCreatedByField;
        
        private System.DateTime transUpdatedOnField;
        
        private int transUpdatedByField;
        
        private int transStatusField;
        
        private bool transSystemRestrictField;
        
        private System.Nullable<int> transGroupIDField;
        
        private bool transIsCompoundField;
        
        private System.Nullable<int> transTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int transID {
            get {
                return this.transIDField;
            }
            set {
                if ((this.transIDField.Equals(value) != true)) {
                    this.transIDField = value;
                    this.RaisePropertyChanged("transID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> transSystemIndex {
            get {
                return this.transSystemIndexField;
            }
            set {
                if ((this.transSystemIndexField.Equals(value) != true)) {
                    this.transSystemIndexField = value;
                    this.RaisePropertyChanged("transSystemIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> transParticipantID {
            get {
                return this.transParticipantIDField;
            }
            set {
                if ((this.transParticipantIDField.Equals(value) != true)) {
                    this.transParticipantIDField = value;
                    this.RaisePropertyChanged("transParticipantID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string transRefID {
            get {
                return this.transRefIDField;
            }
            set {
                if ((object.ReferenceEquals(this.transRefIDField, value) != true)) {
                    this.transRefIDField = value;
                    this.RaisePropertyChanged("transRefID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string transAttachedFiles {
            get {
                return this.transAttachedFilesField;
            }
            set {
                if ((object.ReferenceEquals(this.transAttachedFilesField, value) != true)) {
                    this.transAttachedFilesField = value;
                    this.RaisePropertyChanged("transAttachedFiles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> transInvoiceID {
            get {
                return this.transInvoiceIDField;
            }
            set {
                if ((this.transInvoiceIDField.Equals(value) != true)) {
                    this.transInvoiceIDField = value;
                    this.RaisePropertyChanged("transInvoiceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> transDrAccount {
            get {
                return this.transDrAccountField;
            }
            set {
                if ((this.transDrAccountField.Equals(value) != true)) {
                    this.transDrAccountField = value;
                    this.RaisePropertyChanged("transDrAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> transCrAccount {
            get {
                return this.transCrAccountField;
            }
            set {
                if ((this.transCrAccountField.Equals(value) != true)) {
                    this.transCrAccountField = value;
                    this.RaisePropertyChanged("transCrAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<int> deptId {
            get {
                return this.deptIdField;
            }
            set {
                if ((this.deptIdField.Equals(value) != true)) {
                    this.deptIdField = value;
                    this.RaisePropertyChanged("deptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string transNarration {
            get {
                return this.transNarrationField;
            }
            set {
                if ((object.ReferenceEquals(this.transNarrationField, value) != true)) {
                    this.transNarrationField = value;
                    this.RaisePropertyChanged("transNarration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public decimal transAmount {
            get {
                return this.transAmountField;
            }
            set {
                if ((this.transAmountField.Equals(value) != true)) {
                    this.transAmountField = value;
                    this.RaisePropertyChanged("transAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime transCreatedOn {
            get {
                return this.transCreatedOnField;
            }
            set {
                if ((this.transCreatedOnField.Equals(value) != true)) {
                    this.transCreatedOnField = value;
                    this.RaisePropertyChanged("transCreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int transCreatedBy {
            get {
                return this.transCreatedByField;
            }
            set {
                if ((this.transCreatedByField.Equals(value) != true)) {
                    this.transCreatedByField = value;
                    this.RaisePropertyChanged("transCreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public System.DateTime transUpdatedOn {
            get {
                return this.transUpdatedOnField;
            }
            set {
                if ((this.transUpdatedOnField.Equals(value) != true)) {
                    this.transUpdatedOnField = value;
                    this.RaisePropertyChanged("transUpdatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public int transUpdatedBy {
            get {
                return this.transUpdatedByField;
            }
            set {
                if ((this.transUpdatedByField.Equals(value) != true)) {
                    this.transUpdatedByField = value;
                    this.RaisePropertyChanged("transUpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public int transStatus {
            get {
                return this.transStatusField;
            }
            set {
                if ((this.transStatusField.Equals(value) != true)) {
                    this.transStatusField = value;
                    this.RaisePropertyChanged("transStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public bool transSystemRestrict {
            get {
                return this.transSystemRestrictField;
            }
            set {
                if ((this.transSystemRestrictField.Equals(value) != true)) {
                    this.transSystemRestrictField = value;
                    this.RaisePropertyChanged("transSystemRestrict");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public System.Nullable<int> transGroupID {
            get {
                return this.transGroupIDField;
            }
            set {
                if ((this.transGroupIDField.Equals(value) != true)) {
                    this.transGroupIDField = value;
                    this.RaisePropertyChanged("transGroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public bool transIsCompound {
            get {
                return this.transIsCompoundField;
            }
            set {
                if ((this.transIsCompoundField.Equals(value) != true)) {
                    this.transIsCompoundField = value;
                    this.RaisePropertyChanged("transIsCompound");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public System.Nullable<int> transType {
            get {
                return this.transTypeField;
            }
            set {
                if ((this.transTypeField.Equals(value) != true)) {
                    this.transTypeField = value;
                    this.RaisePropertyChanged("transType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FinProSyncService.SyncSoap")]
    public interface SyncSoap {
        
        // CODEGEN: Generating message contract since element name o from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAccount", ReplyAction="*")]
        FinPro.FinProSyncService.AddAccountResponse AddAccount(FinPro.FinProSyncService.AddAccountRequest request);
        
        // CODEGEN: Generating message contract since element name o from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAccount", ReplyAction="*")]
        FinPro.FinProSyncService.UpdateAccountResponse UpdateAccount(FinPro.FinProSyncService.UpdateAccountRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteAccount", ReplyAction="*")]
        FinPro.FinProSyncService.DeleteAccountResponse DeleteAccount(FinPro.FinProSyncService.DeleteAccountRequest request);
        
        // CODEGEN: Generating message contract since element name o from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTransaction", ReplyAction="*")]
        FinPro.FinProSyncService.AddTransactionResponse AddTransaction(FinPro.FinProSyncService.AddTransactionRequest request);
        
        // CODEGEN: Generating message contract since element name o from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTransaction", ReplyAction="*")]
        FinPro.FinProSyncService.UpdateTransactionResponse UpdateTransaction(FinPro.FinProSyncService.UpdateTransactionRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteTransaction", ReplyAction="*")]
        FinPro.FinProSyncService.DeleteTransactionResponse DeleteTransaction(FinPro.FinProSyncService.DeleteTransactionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAccount", Namespace="http://tempuri.org/", Order=0)]
        public FinPro.FinProSyncService.AddAccountRequestBody Body;
        
        public AddAccountRequest() {
        }
        
        public AddAccountRequest(FinPro.FinProSyncService.AddAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FinPro.FinProSyncService.objAccount o;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pass;
        
        public AddAccountRequestBody() {
        }
        
        public AddAccountRequestBody(FinPro.FinProSyncService.objAccount o, string id, string pass) {
            this.o = o;
            this.id = id;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public FinPro.FinProSyncService.AddAccountResponseBody Body;
        
        public AddAccountResponse() {
        }
        
        public AddAccountResponse(FinPro.FinProSyncService.AddAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddAccountResponseBody {
        
        public AddAccountResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAccount", Namespace="http://tempuri.org/", Order=0)]
        public FinPro.FinProSyncService.UpdateAccountRequestBody Body;
        
        public UpdateAccountRequest() {
        }
        
        public UpdateAccountRequest(FinPro.FinProSyncService.UpdateAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FinPro.FinProSyncService.objAccount o;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pass;
        
        public UpdateAccountRequestBody() {
        }
        
        public UpdateAccountRequestBody(FinPro.FinProSyncService.objAccount o, string id, string pass) {
            this.o = o;
            this.id = id;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public FinPro.FinProSyncService.UpdateAccountResponseBody Body;
        
        public UpdateAccountResponse() {
        }
        
        public UpdateAccountResponse(FinPro.FinProSyncService.UpdateAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateAccountResponseBody {
        
        public UpdateAccountResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteAccount", Namespace="http://tempuri.org/", Order=0)]
        public FinPro.FinProSyncService.DeleteAccountRequestBody Body;
        
        public DeleteAccountRequest() {
        }
        
        public DeleteAccountRequest(FinPro.FinProSyncService.DeleteAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int accNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pass;
        
        public DeleteAccountRequestBody() {
        }
        
        public DeleteAccountRequestBody(int accNo, string id, string pass) {
            this.accNo = accNo;
            this.id = id;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public FinPro.FinProSyncService.DeleteAccountResponseBody Body;
        
        public DeleteAccountResponse() {
        }
        
        public DeleteAccountResponse(FinPro.FinProSyncService.DeleteAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteAccountResponseBody {
        
        public DeleteAccountResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTransaction", Namespace="http://tempuri.org/", Order=0)]
        public FinPro.FinProSyncService.AddTransactionRequestBody Body;
        
        public AddTransactionRequest() {
        }
        
        public AddTransactionRequest(FinPro.FinProSyncService.AddTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FinPro.FinProSyncService.objTransaction o;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pass;
        
        public AddTransactionRequestBody() {
        }
        
        public AddTransactionRequestBody(FinPro.FinProSyncService.objTransaction o, string id, string pass) {
            this.o = o;
            this.id = id;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTransactionResponse", Namespace="http://tempuri.org/", Order=0)]
        public FinPro.FinProSyncService.AddTransactionResponseBody Body;
        
        public AddTransactionResponse() {
        }
        
        public AddTransactionResponse(FinPro.FinProSyncService.AddTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddTransactionResponseBody {
        
        public AddTransactionResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTransaction", Namespace="http://tempuri.org/", Order=0)]
        public FinPro.FinProSyncService.UpdateTransactionRequestBody Body;
        
        public UpdateTransactionRequest() {
        }
        
        public UpdateTransactionRequest(FinPro.FinProSyncService.UpdateTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FinPro.FinProSyncService.objTransaction o;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pass;
        
        public UpdateTransactionRequestBody() {
        }
        
        public UpdateTransactionRequestBody(FinPro.FinProSyncService.objTransaction o, string id, string pass) {
            this.o = o;
            this.id = id;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTransactionResponse", Namespace="http://tempuri.org/", Order=0)]
        public FinPro.FinProSyncService.UpdateTransactionResponseBody Body;
        
        public UpdateTransactionResponse() {
        }
        
        public UpdateTransactionResponse(FinPro.FinProSyncService.UpdateTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateTransactionResponseBody {
        
        public UpdateTransactionResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteTransaction", Namespace="http://tempuri.org/", Order=0)]
        public FinPro.FinProSyncService.DeleteTransactionRequestBody Body;
        
        public DeleteTransactionRequest() {
        }
        
        public DeleteTransactionRequest(FinPro.FinProSyncService.DeleteTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int transNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pass;
        
        public DeleteTransactionRequestBody() {
        }
        
        public DeleteTransactionRequestBody(int transNo, string id, string pass) {
            this.transNo = transNo;
            this.id = id;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteTransactionResponse", Namespace="http://tempuri.org/", Order=0)]
        public FinPro.FinProSyncService.DeleteTransactionResponseBody Body;
        
        public DeleteTransactionResponse() {
        }
        
        public DeleteTransactionResponse(FinPro.FinProSyncService.DeleteTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteTransactionResponseBody {
        
        public DeleteTransactionResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SyncSoapChannel : FinPro.FinProSyncService.SyncSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SyncSoapClient : System.ServiceModel.ClientBase<FinPro.FinProSyncService.SyncSoap>, FinPro.FinProSyncService.SyncSoap {
        
        public SyncSoapClient() {
        }
        
        public SyncSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SyncSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyncSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyncSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinPro.FinProSyncService.AddAccountResponse FinPro.FinProSyncService.SyncSoap.AddAccount(FinPro.FinProSyncService.AddAccountRequest request) {
            return base.Channel.AddAccount(request);
        }
        
        public void AddAccount(FinPro.FinProSyncService.objAccount o, string id, string pass) {
            FinPro.FinProSyncService.AddAccountRequest inValue = new FinPro.FinProSyncService.AddAccountRequest();
            inValue.Body = new FinPro.FinProSyncService.AddAccountRequestBody();
            inValue.Body.o = o;
            inValue.Body.id = id;
            inValue.Body.pass = pass;
            FinPro.FinProSyncService.AddAccountResponse retVal = ((FinPro.FinProSyncService.SyncSoap)(this)).AddAccount(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinPro.FinProSyncService.UpdateAccountResponse FinPro.FinProSyncService.SyncSoap.UpdateAccount(FinPro.FinProSyncService.UpdateAccountRequest request) {
            return base.Channel.UpdateAccount(request);
        }
        
        public void UpdateAccount(FinPro.FinProSyncService.objAccount o, string id, string pass) {
            FinPro.FinProSyncService.UpdateAccountRequest inValue = new FinPro.FinProSyncService.UpdateAccountRequest();
            inValue.Body = new FinPro.FinProSyncService.UpdateAccountRequestBody();
            inValue.Body.o = o;
            inValue.Body.id = id;
            inValue.Body.pass = pass;
            FinPro.FinProSyncService.UpdateAccountResponse retVal = ((FinPro.FinProSyncService.SyncSoap)(this)).UpdateAccount(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinPro.FinProSyncService.DeleteAccountResponse FinPro.FinProSyncService.SyncSoap.DeleteAccount(FinPro.FinProSyncService.DeleteAccountRequest request) {
            return base.Channel.DeleteAccount(request);
        }
        
        public void DeleteAccount(int accNo, string id, string pass) {
            FinPro.FinProSyncService.DeleteAccountRequest inValue = new FinPro.FinProSyncService.DeleteAccountRequest();
            inValue.Body = new FinPro.FinProSyncService.DeleteAccountRequestBody();
            inValue.Body.accNo = accNo;
            inValue.Body.id = id;
            inValue.Body.pass = pass;
            FinPro.FinProSyncService.DeleteAccountResponse retVal = ((FinPro.FinProSyncService.SyncSoap)(this)).DeleteAccount(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinPro.FinProSyncService.AddTransactionResponse FinPro.FinProSyncService.SyncSoap.AddTransaction(FinPro.FinProSyncService.AddTransactionRequest request) {
            return base.Channel.AddTransaction(request);
        }
        
        public void AddTransaction(FinPro.FinProSyncService.objTransaction o, string id, string pass) {
            FinPro.FinProSyncService.AddTransactionRequest inValue = new FinPro.FinProSyncService.AddTransactionRequest();
            inValue.Body = new FinPro.FinProSyncService.AddTransactionRequestBody();
            inValue.Body.o = o;
            inValue.Body.id = id;
            inValue.Body.pass = pass;
            FinPro.FinProSyncService.AddTransactionResponse retVal = ((FinPro.FinProSyncService.SyncSoap)(this)).AddTransaction(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinPro.FinProSyncService.UpdateTransactionResponse FinPro.FinProSyncService.SyncSoap.UpdateTransaction(FinPro.FinProSyncService.UpdateTransactionRequest request) {
            return base.Channel.UpdateTransaction(request);
        }
        
        public void UpdateTransaction(FinPro.FinProSyncService.objTransaction o, string id, string pass) {
            FinPro.FinProSyncService.UpdateTransactionRequest inValue = new FinPro.FinProSyncService.UpdateTransactionRequest();
            inValue.Body = new FinPro.FinProSyncService.UpdateTransactionRequestBody();
            inValue.Body.o = o;
            inValue.Body.id = id;
            inValue.Body.pass = pass;
            FinPro.FinProSyncService.UpdateTransactionResponse retVal = ((FinPro.FinProSyncService.SyncSoap)(this)).UpdateTransaction(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinPro.FinProSyncService.DeleteTransactionResponse FinPro.FinProSyncService.SyncSoap.DeleteTransaction(FinPro.FinProSyncService.DeleteTransactionRequest request) {
            return base.Channel.DeleteTransaction(request);
        }
        
        public void DeleteTransaction(int transNo, string id, string pass) {
            FinPro.FinProSyncService.DeleteTransactionRequest inValue = new FinPro.FinProSyncService.DeleteTransactionRequest();
            inValue.Body = new FinPro.FinProSyncService.DeleteTransactionRequestBody();
            inValue.Body.transNo = transNo;
            inValue.Body.id = id;
            inValue.Body.pass = pass;
            FinPro.FinProSyncService.DeleteTransactionResponse retVal = ((FinPro.FinProSyncService.SyncSoap)(this)).DeleteTransaction(inValue);
        }
    }
}
